<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="salon-content">
    <div class="wrapper">
        <div class="content-left">
            <?=$this->ShowUrlBack($this->salon);?>
            <?=$this->ShowSalonHeader($this->salon);?>
            <? if (isset($this->contentPage['url']) && !empty($this->contentPage['url'])): ?>
                <div class="more-info">
                    <span class="white-lable">Узнать больше о наслаждении, </span></br>
                    <span class="red-lable">которое получите в салоне</span>
                    <a href="<?=$this->contentPage['url']->getFieldText();?>" target="_blank"><?=$this->contentPage['url']->getFieldText();?></a>
                </div>
            <? endif; ?>
            <? if (count($this->girls) > 0): ?>
            <div class="relax-recommends">
                <div class="header"><?=Kernel_Block::getText('Девушки салона', $this->blocks);?></div>
                <div class="model-item-container">
                    <? foreach ($this->girls as $k=>$girl): ?>
                        <? $content = $girl->getContent()->getFields();?>
                        <div class="model-item-box">
                            <div class="model-item">
                                <div class="name">
                                    <a href="<?=$girl->path()?>"><?=$content['name']->getFieldText();?></a>, <?=$girl->getAge();?>
                                </div>
                                <? $galery = $girl->getGallery(); ?>
                                <? if (!is_null($galery)): ?>
                                <a href="<?=$girl->path()?>">
                                    <? $photo = $galery->getFirstPhoto(); ?>
                                    <img src="<?=$photo->getPath('150', true);?>" width="150px" alt="Массажистка <?=$content['name']->getFieldText();?>">
                                </a>
                                <? endif; ?>
                                <a class="comment-value"><?=count($girl->getComments())?> отзывов</a>
                            </div>
                        </div>
                    <? endforeach; ?>
                </div>
            </div>
            <? endif; ?>
            <?=$this->ShowSalonSubscribeBox()?>
            <?=$this->ShowTopSalonCity()?>
            <?=$this->ShowTopGirlCity()?>
        </div>
        <aside class="sidebar-right">
        <div class="sidebar-right-widget">
            <h3>Отзывы о салоне <span>(36)</span></h3>
            <a class="leave-comment" href="#">Оставить отзыв</a>
            <ul>
                <li>
                    <span class="author">Миша</span>
                    <time>19 мая 2013 в 01:50</time>
                    <p class="author-comment">— Был сегодня в Вашем салоне. Мне очень понравилась массажистка Влада. Заеду
                        еще. Ты мастер своего дела.</p>
                </li>
                <li>
                    <span class="author">Миша</span>
                    <time>19 мая 2013 в 01:50</time>
                    <p class="author-comment">— Настя ты просто ангел!!! У тебя прекрасное тело а грудь мм....
                        Ты профессионал! Рекомендую всем!!!!</p>
                </li>
                <li>
                    <span class="author">Миша</span>
                    <time>19 мая 2013 в 01:50</time>
                    <p class="author-comment">— Дорогие мужчины!Спасибо за прекрасные слова в наш адрес.Мы всегда рады Вас
                        видеть.Хотим ответить на ваши отзывы:-Лиза вернулась.А на счет затасканых..тупых..и
                        антисанитарии-могу ответить-это ложь.Достаточно зайти на наш сайт и посмотреть на фото где шикарные
                        девченки в аппартаментах с евроремонтом.Да и встречаем мы всех с улыбкой-так заведено.И уходит от
                        нас ни с чем -один из пятидесяти.А то и отправляем сами если пришел "невминяшка"...А у нашего гостя
                        видимо денег не хватило и ему отказали, вот и расстроился бедолага и решил грязью облить.Но это его
                        мнение и мы его уважаем.А Вам советуем самим убедиться.Приходите,всегда Вам рады.</p>
                </li>
            </ul>
            <div class="prev-next-comments-box">
                <a class="prev-comments" href="#">&larr; Предыдущие</a>
                <a class="next-comments" href="#">Следующие &rarr;</a>
            </div>
        </div>
    </aside>
    </div>
</sections>