<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="salon-content">
    <div class="wrapper">
        <div class="content-left">
            <?=$this->ShowUrlBack($this->salon);?>
            <?=$this->ShowSalonHeader($this->salon);?>
            <? if (isset($this->contentPage['url']) && !empty($this->contentPage['url'])): ?>
                <div class="more-info">
                    <span class="white-lable">Узнать больше о наслаждении, </span></br>
                    <span class="red-lable">которое получите в салоне</span>
                    <a href="<?=$this->contentPage['url']->getFieldText();?>" target="_blank"><?=$this->contentPage['url']->getFieldText();?></a>
                </div>
            <? endif; ?>
            <? if (count($this->girls) > 0): ?>
            <div class="relax-recommends">
                <div class="header"><?=Kernel_Block::getText('Девушки салона', $this->blocks);?></div>
                <div class="model-item-container">
                    <? foreach ($this->girls as $k=>$girl): ?>
                        <? $content = $girl->getContent()->getFields();?>
                        <div class="model-item-box">
                            <div class="model-item">
                                <div class="name">
                                    <a href="<?=$girl->path()?>"><?=$content['name']->getFieldText();?></a>, <?=$girl->getAge();?>
                                </div>
                                <? $galery = $girl->getGallery(); ?>
                                <? if (!is_null($galery)): ?>
                                <a href="<?=$girl->path()?>">
                                    <? $photo = $galery->getFirstPhoto(); ?>
                                    <img src="<?=$photo->getPath('150', true);?>" width="150px" alt="Массажистка <?=$content['name']->getFieldText();?>">
                                </a>
                                <? endif; ?>
                                <a class="comment-value"><?=count($girl->getComments())?> отзывов</a>
                            </div>
                        </div>
                    <? endforeach; ?>
                </div>
            </div>
            <? endif; ?>
            <?=$this->ShowSalonSubscribeBox()?>
            <?=$this->ShowTopSalonCity()?>
            <?=$this->ShowTopGirlCity()?>
        </div>
        <aside class="sidebar-right">
        <div class="sidebar-right-widget">
            <h3>Отзывы о салоне <span>(<?=count($this->salon->getComments())?>)</span></h3>
            <a class="leave-comment" href="#">Оставить отзыв</a>
            <ul>
                <? $i = 1; ?>
                <? $j = 1; ?>
                <? foreach ($this->salon->getComments() as $comment): ?>
                    <li <? if ($j > 1): ?>style="display: none;"<? endif;?> class="comment_part_<?=$j?>">
                        <span class="author"><?=$comment->getCommentNick()?></span>
                        <time><?=Application_Model_Kernel_Date_Manager::formatDate($comment->getCommentDate(), Application_Model_Kernel_Date_Manager::TYPE_USER_VIEW)?></time>
                        <p class="author-comment">— <?=$comment->getCommentText()?></p>
                    </li>
                    <? if ($i == 3) {
                        $i = 0;
                        $j++;
                    }
                    ?>
                    <? $i++; ?>
                <? endforeach; ?>
            </ul>
<!--            <div class="prev-next-comments-box">-->
<!--                <a class="prev-comments" href="#">&larr; Предыдущие</a>-->
<!--                <a class="next-comments" href="#">Следующие &rarr;</a>-->
<!--            </div>-->
        </div>
    </aside>
    </div>
</sections>