<?=$this->partial('blocks/menus/blog.phtml');?>
<form action="<?=$this->url(array())?>" method="post" id="PageForm">
    <div id="tabs">
        <?php if (sizeof($this->langs) > 1): ?>
            <ul>
                <?php foreach ($this->langs as $lang): ?>
                    <li><a href="#<?=$lang->getIsoName()?>"><?=$lang->getFullName()?></a></li>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
        <?php foreach ($this->langs as $lang): ?>
            <div id="<?=$lang->getIsoName()?>">
                <table class="zebra edit">
                    <tr class="grey">
                        <td width="193" class="first">Имя:</td>
                        <td><input name="content[<?=$lang->getId()?>][name]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['name'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['name']) : ''?>" /></td>
                    </tr>
                    <tr class="">
                        <td width="193" class="first">Head:</td>
                        <td><input name="content[<?=$lang->getId()?>][head]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['head'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['head']) : ''?>" /></td>
                    </tr>
                    <tr class="">
                        <td width="193" class="first">Титл:</td>
                        <td><input name="content[<?=$lang->getId()?>][title]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['title'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['title']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Дескрипшин:</td>
                        <td><input name="content[<?=$lang->getId()?>][description]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['description'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['description']) : ''?>" /></td>
                    </tr>
                    <tr class="">
                        <td width="193" class="first">Кейвордс:</td>
                        <td><input name="content[<?=$lang->getId()?>][keywords]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['keywords'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['keywords']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Размер груди:</td>
                        <td><input name="content[<?=$lang->getId()?>][grudi]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['grudi'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['grudi']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Вес:</td>
                        <td><input name="content[<?=$lang->getId()?>][ves]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['ves'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['ves']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Талия:</td>
                        <td><input name="content[<?=$lang->getId()?>][talia]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['talia'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['talia']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Рост:</td>
                        <td><input name="content[<?=$lang->getId()?>][rost]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['rost'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['rost']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Бедра:</td>
                        <td><input name="content[<?=$lang->getId()?>][bedro]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['bedro'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['bedro']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Волосы:</td>
                        <td><input name="content[<?=$lang->getId()?>][volos]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['volos'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['volos']) : ''?>" /></td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Глаза:</td>
                        <td><input name="content[<?=$lang->getId()?>][glaz]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['glaz'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['glaz']) : ''?>" /></td>
                    </tr>
                </table>
            </div>
        <?php endforeach ?>
    </div>
    <table class="zebra edit">
        <tbody>
        <tr class="grey">
            <td width="193" class="first">Возвраст:</td>
            <td>
                <input name="age" style="width:255px" type="text" class="field" value="<?= (isset($_POST['age'])) ? $_POST['age'] : '' ?>" />
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">URL:</td>
            <td>
                <input name="realName" type="text" class="field" style="background-color: #F2F2F2; width:10px;" disabled="disabled" value="/" />
                <input name="url" style="width:255px" type="text" class="field" value="<?= (isset($_POST['url'])) ? $_POST['url'] : '' ?>" disabled="disabled" />
                <input name="realNamehtml" type="text" class="field" style="background-color: #F2F2F2; width:30px;" disabled="disabled" value=".html" />
            </td>
        </tr>
        </tbody>
    </table>
    <table class="zebra edit">
        <tbody>
            <tr class="grey">
                <td>&nbsp;</td>
                <td>
                    <div class="m10 center">
                        <input id="idPage" type="hidden" name="idPage" value="<?= $this->idPage ?>" />
                        <a href="javascript:SubmitPageFrom();" class="button_blue">Сохранить</a>
                        <a href="<?=$this->url(array('salon_id'=>$this->salon_id),'admin-girl-index')?>" class="button_grey">Отменить</a>
                    </div>
                </td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    </table>
</form>
