<?= $this->partial('blocks/menus/top.phtml'); ?>
<script>
    function confirmDelete()
    {
        if (!confirm('Уверены что хотите удалить?')) {
            return false;
        }

        return true;
    }
</script>
<table class="zebra" id="projectsTable">
    <thead>
    <tr>
        <td style="width: 10%;"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </thead>
    <?php if (count($this->girls)): ?>
        <?php $class = ''; ?>
        <tbody>
        <? $i = 0; ?>
        <? foreach ($this->girls->data as $item): ?>
            <? $content = $item->getContent()->getFields(); ?>
            <? $i++; ?>
            <? ($class === 'grey') ? $class = '' : $class = 'grey'; ?>
            <tr id="<?= $item->getId() ?>" class="<?= $class; ?> id_<?= $item->getId() ?>">
                <td>
                    <a href="<?= $this->url(array ('id' => $item->getId(), 'salon_id'=>$this->salon_id), 'admin-girl-edit'); ?>" class="edit"
                       title="Редактировать">
                        <img src="/static/admin/images/edit.png" alt="Edit" width="16" height="16"/>
                    </a>
                    &nbsp;
                    <a href="<?=$this->url(array(
                                                'idGallery' => $item->getIdGallery(),
                                                'fromType' => Application_Model_Kernel_Page::TYPE_GIRL
                                           ),'admin-gallery-photos')?>">
                        <img src="/static/admin/images/menu_icons/images-stack.png" alt="Edit" width="16" height="16" />
                    </a>
                </td>
                <td style="padding-left:10px;">
                    <?=$content['name']->getFieldText();?>
                </td>
                <td style="text-align: right;"></td>
                <td style="text-align: right;">
                    <a href="<?=$item->path()?>" target="_black" title="Просмотр"><img src="/static/admin/images/eye.png" alt="" width="16" height="16"></a>&nbsp;&nbsp;
                    <a href="javascript:changeStatus(<?=$item->getIdPage()?>, 1);" class="<?=$item->getStatus();?>" title="<?=$StatusTitle;?>">
                        <img class="page_status_<?=$item->getIdPage()?>" src="/static/admin/images/show_<?=$item->getStatus();?>.png" alt="" width="15" height="15">
                    </a>
                </td>
                <td style="text-align: left;">
                    <a href="<?= $this->url(array ('id' => $item->getId(), 'salon_id'=>$this->salon_id), 'admin-girl-delete'); ?>" class="delete" title="Удалить" onclick="return confirmDelete();"><img src="/static/admin/images/icon_delete.gif" alt=""
                                                                    width="9" height="8"/></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>

<input id="statusUrl" type="hidden" value="<?=$this->url(array(),'admin-page-status')?>"/>