<? $content = $this->salon->getContent()->getFields();?>
<? $area = $this->salon->getArea();?>
<? $areaContent = $area->getContent()->getFields();?>
<article class="salon-item-article">
    <div class="salon-title">
        <a href="<?=Kernel_City::getUrlForLink($this->salon->getCity())?><?=$this->salon->getRoute()->getUrl();?>" class="title-link"><?=$content['name']->getFieldText();?></a>
        <a href="<?=Kernel_City::getUrlForLink($this->salon->getCity())?><?=$this->salon->getRoute()->getUrl();?>">
            <img src="<?=$this->salon->getPhoto1()->getPath('80', true);?>" alt="Салон эротического массажа <?=$content['name']->getFieldText();?>" width="80">
        </a>
        <a class="comment-value" href="<?=Kernel_City::getUrlForLink($this->salon->getCity())?><?=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-review');?>"><?=count($this->salon->getComments())?> отзывов</a>
    </div>
    <div class="salon-model-box">
        <div class="salon-site">
            <a target="_blank" href="<?=isset($content['url'])?$content['url']->getFieldText():''?>"><?=isset($content['url'])?$content['url']->getFieldText():''?></a>
        </div>
        <div class="salon-model">
            <p>Девушки салона:</p>
            <? foreach ($this->salon->getGirls() as $key=>$girl): ?>
                <? if( $key >= 3 ) break; ?>
                <? $contentGirl = $girl->getContent()->getFields();?>
                <? $photo = $girl->getGallery()->getFirstPhoto(); ?>
                <a href="<?=Kernel_City::getUrlForLink($this->salon->getCity())?><?=$this->salon->getRoute()->getUrl();?>#girl_<?=$girl->getId()?>" class="salonModelItem">
                    <img alt="Массажистка <?=$contentGirl->getFText('name');?>"
                         class="lazy" data-original="<?=$photo->getPath('120:120');?>" width="120"/>
                </a>
            <? endforeach; ?>
            <div class="clear"></div>
            <a class="desc-link" href="<?=Kernel_City::getUrlForLink($this->salon->getCity())?><?=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-review');?>">Общие описание и отзывы (<?=count($this->salon->getComments())?>)</a>
        </div>
    </div>
</article>