<?php if ( $this->pageCount > 1 ): ?>
    <div class="pagination-box">
        <?php if (isset($this->previous)): ?>
            <? if($this->previous != 1): ?>
                <a class="prev-pagin-link" href="<?= $this->url(array(),'default-type-massage'.$this->previous) ?>"
                    >&larr; Предыдущая</a>
            <? else: ?>
                <a href="<?= $this->url(array(),'default-type-massage') ?>"
                    ></a>
            <? endif; ?>
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                    <? if($page != 1): ?>
                        <a href="<?= $this->url(array(),'default-type-massage'.$page) ?>"
                           ><?= $page; ?></a>
                    <? else: ?>
                        <a href="<?= $this->url(array(),'default-type-massage') ?>"
                            ><?= $page; ?></a>
                    <? endif; ?>
            <?php else: ?>
                <span><?= $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
            <a class="next-pagin-link" href="<?= $this->url(array(),'default-type-massage'.$this->next) ?>">Следующая &rarr;</a>
        <?php endif; ?>
    </div>
<?php endif; ?>