<!--<div class="salonHeader" style="background: url(--><?//=$this->salon->getPhoto2()->getPath('939:261');?><!--) no-repeat center center;">-->
<!--    <div class="salonMetaBox">-->
<!--        <div class="singleSalonLogo">-->

<!--        </div>-->
<!--        <h2>--><?//=$this->contentPage['name']->getFieldText();?><!--</h2>-->
<!--        <div class="clear"></div>-->
<!--        <a class="location" href="--><?//=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-map');?><!--">--><?//=$this->contentPage['adress']->getFieldText();?><!--</a>-->
<!--        <div class="singleSalonCommentsBox">-->
<!--            <a href="--><?//=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-review');?><!--">– --><?//=$this->countAllComments; ?><!-- --><?//=Kernel_Block::getText('отзывов', $this->blocks);?><!--</a>-->
<!--            <em>--><?//=Kernel_Block::getText('положительных', $this->blocks);?><!-- – --><?//=$this->countGoodComments; ?><!--</em><br>-->
<!--            <em>--><?//=Kernel_Block::getText('нейтральных', $this->blocks);?><!-- – --><?//=$this->countNormalComments; ?><!--</em><br>-->
            <em><?=Kernel_Block::getText('отрицательных', $this->blocks);?> – <?=$this->countBadComments; ?></em>
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="salon-content">
    <h1>Салон «<?=$this->contentPage['name']->getFieldText();?>»</h1>
    <div class="first-cell">
        <a href="#">
            <img src="<?=$this->salon->getPhoto1()->getPath('80', true);?>" width="80px" alt="Салон эротического массажа <?=$this->contentPage['name']->getFieldText();?>">
        </a>
        <span>Киев</span>
        <a class="comment-value" href="<?=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-review');?>"><?=$this->countAllComments;?> отзывов</a>
    </div>
    <div class="second-cell">
        <div class="top"><span>Адрес:</span> <?=$this->contentPage['adress']->getFieldText();?> (<a href="#">на карте</a>)</div>
        <div class="desc">
            <span>Описание:</span> <?=$this->contentPage['content']->getFieldText();?>
        </div>
    </div>
</div>