<div class="subscribe-box">
    <div class="left-cell">
        <span class="subs-white">Подпишись на нашу рассылку</span>
        <span class="subs-red">и всегда будь в курсе:</span>
        <ul>
            <li>новых девушек на портале</li>
            <li>новых салонов в нашем каталоге</li>
            <li>новых возможностях наслаждения</li>
        </ul>
    </div>
    <div class="right-cell">
        <form>
            <span>Ваша электронная почта</span>
            <input type="text" name="" id=""/>
            <input type="submit" name="" id="" value="Подписаться"/>
        </form>
    </div>
</div>