<div class="salon-content">
    <h1>Салон «<?=$this->contentPage['name']->getFieldText();?>»</h1>
    <div class="first-cell">
        <a href="#">
            <img src="<?=$this->salon->getPhoto1()->getPath('80', true);?>" width="80px" alt="Салон эротического массажа <?=$this->contentPage['name']->getFieldText();?>">
        </a>
        <span>Киев</span>
        <a class="comment-value" href="<?=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-review');?>"><?=$this->countAllComments;?> отзывов</a>
    </div>
    <div class="second-cell">
        <div class="top"><span>Адрес:</span> <?=$this->contentPage['adress']->getFieldText();?> (<a href="#">на карте</a>)</div>
        <div class="desc">
            <span>Описание:</span> <?=$this->contentPage['content']->getFieldText();?>
        </div>
    </div>
</div>