<div class="new-salon">
    <div class="header">
        Рекомендуем салоны в городе Киев
    </div>
    <div id="new-salon-carousel" class="content">
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">5 комнат</a>
                <a href="#"><img src="images/salon-item.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">Milos</a>
                <a href="#"><img src="images/salon-item-2.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">5 комнат</a>
                <a href="#"><img src="images/salon-item.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">5 комнат</a>
                <a href="#"><img src="images/salon-item-2.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">Amur</a>
                <a href="#"><img src="images/salon-item.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">Milos</a>
                <a href="#"><img src="images/salon-item-2.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">5 комнат</a>
                <a href="#"><img src="images/salon-item.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="salon-item-box">
            <div class="salon-item">
                <a href="#">Amur</a>
                <a href="#"><img src="images/salon-item-2.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
    </div>
    <a id="new-salon-prev" href="#"></a>
    <a id="new-salon-next" href="#"></a>
    <a class="all-item-carousel" href="/">Все салоны &rarr;</a>
</div>