<div class="new-models">
    <div class="header">
        Популярные девушки города Киев
    </div>
    <div id="new-model-carousel" class="content">
        <? foreach ($this->salons->data as $salon): ?>
            <? foreach ($salon->getGirls() as $girl): ?>
                <? if (!$girl->isPopular()) continue; ?>
                <? $girlContent = $girl->getContent()->getFields(); ?>
                <div class="model-item-box">
                    <div class="model-item">
                        <div class="name">
                            <a href="<?=$girl->path(); ?>"><?=$girlContent->getFText('name'); ?></a>, <?=$girl->getAge();?>
                        </div>
                        <? $girlGallery = $girl->getGallery(); ?>
                        <? if (!is_null($girlGallery) && $girlGallery->getPhotoCount() > 0): ?>
                            <a href="<?=$girl->path()?>">
                                <? $photo = $girlGallery->getFirstPhoto(); ?>
                                <img src="<?=$photo->getPath('150', true);?>" width="150px" alt="Массажистка <?=$girlContent->getFText('name');?>">
                            </a>
                        <? endif; ?>
                        <a class="comment-value"><?=count($girl->getComments())?> отзывов</a>
                    </div>
                </div>
            <? endforeach; ?>
        <? endforeach; ?>
    </div>
    <a id="new-model-prev" href="#"></a>
    <a id="new-model-next" href="#"></a>
    <a class="all-item-carousel" href="#">Все девушки &rarr;</a>
</div>