<?php $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<? $city = Kernel_City::findCityFromUrl();?>
<sections class="home-content">
<? if (!$city): ?>
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <?=$this->ShowWidgetBanner();?>
            <?=$this->ShowWidgetComments();?>
            <?=$this->ShowWidgetAdvertisings();?>
            <?=$this->ShowWidgetArticles();?>
        </aside>
        <div class="content-right">
    <article>
        <h2>Весь эротический массаж в Украине</h2>

        <p>Сайт <a href="#">My-Relax</a> самый полный каталог салонов эротического массажа в Киеве и Украине. Для каждого
            салона Вы найдете: краткое описание, географическое месторасположение на карте города, фотографии девушек,
            отзывы и рейтинги от посетителей салонов, виды эротического массажа и его стоимость.</p>
    </article>
    <div class="warning">
        <span class="warning-1">Cалоны, размещенные в каталоге My-Relax,</span>
        <span class="warning-2">не предоставляют</span>
        <span class="warning-3">услуг интимного характера !!!</span>
    </div>
    <div class="relax-recommends">
        <div class="header">
            My-Relax рекомендует:
            <small>лучшие салоны эротического массажа</small>
        </div>
        <div id="salon-carousel" class="content">
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">Milos</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">Milos</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">Amur</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">Amur</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">Milos</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">Milos</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">5 комнат</a>
                    <a href="#"><img src="/static/default/images/salon-item.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="salon-item-box">
                <div class="salon-item">
                    <a href="#">Amur</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="salon-item">
                    <a href="#">Amur</a>
                    <a href="#"><img src="/static/default/images/salon-item-2.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
        </div>
        <a id="salon-prev" href="#"></a>
        <a id="salon-next" href="#"></a>
        <a class="all-item-carousel" href="/">Все салоны &rarr;</a>
    </div>
    <div class="top-models">
        <div class="header">
            ТОП девушки
            <small>салонов эротического массажа</small>
        </div>
        <div id="model-carousel" class="content">
            <div class="model-item-box">
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model1g.png"></a>
                    <span class="city">Днепропетровск</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model1g.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="model-item-box">
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Днепропетровск</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="model-item-box">
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Днепропетровск</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="model-item-box">
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model1g.png"></a>
                    <span class="city">Днепропетровск</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model1g.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="model-item-box">
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Днепропетровск</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
            <div class="model-item-box">
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Днепропетровск</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
                <div class="model-item">
                    <div class="name">
                        <a href="#">Виктория</a>, 22
                    </div>
                    <a href="#"><img src="/static/default/images/model2g.png"></a>
                    <span class="city">Киев</span>
                    <a class="comment-value">26 отзывов</a>
                </div>
            </div>
        </div>
        <a id="model-prev" href="#"></a>
        <a id="model-next" href="#"></a>
        <a class="all-item-carousel" href="#">Все девушки &rarr;</a>
    </div>
    <?=$this->ShowSalonSubscribeBox()?>
    <?=$this->ShowNewGirls()?>
    <?=$this->ShowNewSalons()?>
    <article>
        <?php echo $this->text ?>
    </article>
    <?=$this->ShowNewMassages()?>
    </div>
    </div>
<? else: ?>
    <? $cityConten = $city->getContent()->getFields();?>
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <?=$this->ShowWidgetSubscribe();?>
            <?=$this->ShowWidgetBanner();?>
            <?=$this->ShowWidgetComments();?>
            <?=$this->ShowWidgetNewSalons();?>
        </aside>
        <div class="content-right">
            <article>
                <h2>Весь эротический массаж в Украине</h2>
                <p>Сайт <a href="#">My-Relax</a> самый полный каталог салонов эротического массажа в Киеве и Украине. Для каждого салона Вы найдете: краткое описание, географическое месторасположение на карте города, фотографии девушек, отзывы и рейтинги от посетителей салонов, виды эротического массажа и его стоимость.</p>
            </article>
            <?php echo $this->partial('block/list.phtml', array (
                'salons' => $this->salons,
                'siteSetings' => $this->siteSetings
            )) ?>
            <div class="descText">
                <article>
                    <?=$this->text;?>
                </article>
            </div>
        </div>
    </div>
<? endif ?>
</sections>