<?php $this->headScript()->captureStart() ?>
<?php $this->headScript()->captureEnd() ?>
<?php $city = Kernel_City::findCityFromUrl();?>
<sections class="home-content">
<? if (!$city): ?>
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <?=$this->ShowWidgetBanner();?>
            <?=$this->ShowWidgetComments();?>
            <?=$this->ShowWidgetAdvertisings();?>
            <?=$this->ShowWidgetArticles();?>
        </aside>
        <div class="content-right">
    <article>
        <h2>Весь эротический массаж в Украине</h2>

        <p>Сайт <a href="/">My-Relax</a> самый полный каталог салонов эротического массажа в Киеве и Украине. Для каждого
            салона Вы найдете: краткое описание, географическое месторасположение на карте города, фотографии девушек,
            отзывы и рейтинги от посетителей салонов, виды эротического массажа и его стоимость.</p>
    </article>
    <div class="warning">
        <span class="warning-1">Cалоны, размещенные в каталоге My-Relax,</span>
        <span class="warning-2">не предоставляют</span>
        <span class="warning-3">услуг интимного характера !!!</span>
    </div>
    <?=$this->ShowRecommendSalons()?>
    <?=$this->ShowTopGirls()?>
    <?=$this->ShowSalonSubscribeBox()?>
    <?=$this->ShowNewGirls()?>
    <?=$this->ShowNewSalons()?>
    <article>
        <?php echo $this->text ?>
    </article>
    <?=$this->ShowNewMassages()?>
    </div>
    </div>
<? else: ?>
    <? $cityConten = $city->getContent()->getFields();?>
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <?=$this->ShowWidgetSubscribe();?>
            <?=$this->ShowWidgetBanner();?>
            <?=$this->ShowWidgetComments();?>
            <?=$this->ShowWidgetNewSalons();?>
        </aside>
        <div class="content-right">
            <article>
                <h2>Весь эротический массаж в Украине</h2>
                <p>Сайт <a href="#">My-Relax</a> самый полный каталог салонов эротического массажа в Киеве и Украине. Для каждого салона Вы найдете: краткое описание, географическое месторасположение на карте города, фотографии девушек, отзывы и рейтинги от посетителей салонов, виды эротического массажа и его стоимость.</p>
            </article>
            <?php echo $this->partial('block/list.phtml', array (
                'salons' => $this->salons,
                'siteSetings' => $this->siteSetings
            )) ?>
            <div class="descText">
                <article>
                    <?=$this->text;?>
                </article>
            </div>
        </div>
    </div>
<? endif ?>
</sections>