<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="home-content">
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <?=$this->ShowWidgetSubscribe();?>
            <?=$this->ShowWidgetBanner();?>
            <?=$this->ShowWidgetComments();?>
            <?=$this->ShowWidgetNewSalons();?>
        </aside>
        <div class="content-right">
        <article>
            <h2>Весь эротический массаж в Украине</h2>
            <p>Сайт <a href="#">My-Relax</a> самый полный каталог салонов эротического массажа в Киеве и Украине. Для каждого салона Вы найдете: краткое описание, географическое месторасположение на карте города, фотографии девушек, отзывы и рейтинги от посетителей салонов, виды эротического массажа и его стоимость.</p>
        </article>
        <?php echo $this->partial('block/list.phtml', array (
            'salons' => $this->salons,
            'siteSetings' => $this->siteSetings
        )) ?>
        <div class="descText">
            <article>
                <?=$this->text;?>
            </article>
        </div>
    </div>
    </div>
</sections>