<div class="new-models">
    <div class="header">
        Новые девушки
    </div>
    <div id="new-model-carousel" class="content">
        <div class="new-model-item-box">
            <div class="new-model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model1g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="new-model-item-box">
            <div class="new-model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="new-model-item-box">
            <div class="new-model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="new-model-item-box">
            <div class="new-model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model1g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="new-model-item-box">
            <div class="new-model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="new-model-item-box">
            <div class="new-model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
    </div>
    <a id="new-model-prev" href="#"></a>
    <a id="new-model-next" href="#"></a>
    <a class="all-item-carousel" href="#">Все девушки &rarr;</a>
</div>