<div class="top-models">
    <div class="header">
        ТОП девушки
        <small>салонов эротического массажа</small>
    </div>
    <? $i = 1; ?>
    <? $j = 0; ?>
    <div id="model-carousel" class="content">
        <? foreach ($this->girls->data as $girl): ?>
            <? $girlContent = $girl->getContent()->getFields(); ?>
            <? if ($i == 1): ?>
                <div class="model-item-box">
            <? endif; ?>
            <div class="model-item">
                <div class="name">
                    <a href="<?=$girl->path(); ?>"><?=$girlContent->getFText('name'); ?></a>, <?=$girl->getAge();?>
                </div>
                <? $girlGallery = $girl->getGallery(); ?>
                <? if (!is_null($girlGallery) && $girlGallery->getPhotoCount() > 0): ?>
                    <a href="<?=$girl->path()?>">
                        <? $photo = $girlGallery->getFirstPhoto(); ?>
                        <img src="<?=$photo->getPath('150', true);?>" width="150" alt="Массажистка <?=$girlContent->getFText('name');?>">
                    </a>
                <? endif; ?>
                <a class="comment-value"><?=count($girl->getComments())?> отзывов</a>
            </div>
            <? if ($i == 2 || $j==count($this->girls->data)): ?>
                </div>
                <? $i = 0; ?>
            <?endif; ?>
            <? $i++; ?>
            <? $j++; ?>
        <? endforeach; ?>
    </div>
    <a id="model-prev" href="#"></a>
    <a id="model-next" href="#"></a>
    <a class="all-item-carousel" href="<?=$this->url(array(), 'default-list-girls');?>">Все девушки &rarr;</a>
</div>