<div class="top-models">
    <div class="header">
        ТОП девушки
        <small>салонов эротического массажа</small>
    </div>
    <div id="model-carousel" class="content">
        <div class="model-item-box">
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model1g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model1g.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="model-item-box">
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="model-item-box">
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="model-item-box">
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model1g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model1g.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="model-item-box">
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
        <div class="model-item-box">
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Днепропетровск</span>
                <a class="comment-value">26 отзывов</a>
            </div>
            <div class="model-item">
                <div class="name">
                    <a href="#">Виктория</a>, 22
                </div>
                <a href="#"><img src="/static/default/images/model2g.png"></a>
                <span class="city">Киев</span>
                <a class="comment-value">26 отзывов</a>
            </div>
        </div>
    </div>
    <a id="model-prev" href="#"></a>
    <a id="model-next" href="#"></a>
    <a class="all-item-carousel" href="#">Все девушки &rarr;</a>
</div>