<div class="sidebar-widget">
    <h3>Статьи</h3>
    <ul>
        <li>
            <time>19 мая 2013 в 01:50</time>
            <a href="#">Достойный массажный салон должен быть достойным во всем</a>

            <div class="clear"></div>
        </li>
        <li>
            <time>22 мая 2013 в 12:50</time>
            <a href="#">Интимный массаж не только возбуждает</a>

            <div class="clear"></div>
        </li>
        <li>
            <time>07 мая 2013 в 11:50</time>
            <a href="#">Тайский массаж - не всегда эротический</a>

            <div class="clear"></div>
        </li>
    </ul>
    <div class="all-link-right">
        <a href="#" class="all-link">Все статьи &rarr;</a>
    </div>
</div>