<div class="sidebar-widget">
    <h3>Статьи</h3>
    <ul>
        <? foreach ($this->articles->data as $article): ?>
            <? $content = $article->getContent()->getFields(); ?>
            <li>
                <time><?=Application_Model_Kernel_Date_Manager::formatDate($article->getPageEditDate(),Application_Model_Kernel_Date_Manager::TYPE_USER_VIEW)?></time>
                <a href="<?=$article->path()?>"><?=$content->getFText('name')?></a>
                <div class="clear"></div>
            </li>
        <? endforeach; ?>
    </ul>
    <div class="all-link-right">
        <a href="<?=$this->url(array(), 'default-list-article')?>" class="all-link">Все статьи &rarr;</a>
    </div>
</div>