<div class="sidebar-widget comments-widget">
    <h3>Отзывы</h3>
    <ul>
        <li>
            <a href="#"><img src="images/ava.png"></a>
            <a class="author" href="#">Mon - Amour</a>
            <time>19 мая 2013 в 01:50</time>
            <a class="comment" href="#">— Я покупала сертификат для своего мужчины. Большое спасибо, девушкам Даше и Асе.</a>
            <div class="clear"></div>
        </li>
        <li>
            <a href="#"><img src="images/ava.png"></a>
            <a class="author" href="#">Mon - Amour</a>
            <time>19 мая 2013 в 01:50</time>
            <a class="comment" href="#">— Я покупала сертификат для своего мужчины. Большое спасибо, девушкам Даше и Асе.</a>
            <div class="clear"></div>
        </li>
        <li>
            <a href="#"><img src="images/ava.png"></a>
            <a class="author" href="#">Mon - Amour</a>
            <time>19 мая 2013 в 01:50</time>
            <a class="comment" href="#">— Я покупала сертификат для своего мужчины. Большое спасибо, девушкам Даше и Асе.</a>
            <div class="clear"></div>
        </li>
    </ul>
    <div class="all-link-right">
        <a href="#" class="all-comments">Все отзывы &rarr;</a>
    </div>

</div>