<div class="sidebar-widget newsalon-widget">
    <h3>Новые салоны</h3>
    <ul>
        <li>
            <a href="#"><img src="images/salon-item.png"></a>
            <a class="salon-name" href="#">Mon - Amour</a>
            <span>Киев</span>
            <span class="street" href="#">ул. Киквидзе, 1а</span>

            <div class="clear"></div>
        </li>
        <li>
            <a href="#"><img src="images/salon-item.png"></a>
            <a class="salon-name" href="#">Mon - Amour</a>
            <span>Киев</span>
            <span class="street" href="#">ул. Киквидзе, 1а</span>

            <div class="clear"></div>
        </li>
        <li>
            <a href="#"><img src="images/salon-item.png"></a>
            <a class="salon-name" href="#">Mon - Amour</a>
            <span>Киев</span>
            <span class="street" href="#">ул. Киквидзе, 1а</span>

            <div class="clear"></div>
        </li>
    </ul>
    <div class="all-link-right">
        <a href="/" class="all-comments">Все салоны &rarr;</a>
    </div>
</div>