<!DOCTYPE html>
<html lang="uk">
<head>
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content="<?= $this->description ?>"/>
    <meta name="keywords" content="<?= $this->keywords ?>"/>

    <meta name='yandex-verification' content='640b7b0663c2edc7' />
    <?= $this->headText; ?>
    <!--[if lte IE 8]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
    <script type="text/javascript" src="/static/default/js/jquery-1.9.1.min.js"></script>
    <?=$this->siteSetings->getHead();?>
</head>
<body>
<?php echo $this->partial('blocks/header.phtml', array (
    'menu' => $this->menu,
    'blocks' => $this->blocks,
    'siteSetings' => $this->siteSetings,
    'cityContent' => $this->currentCityContent,
    'currentLang' => $this->currentLang,
    'area' => isset($this->area)?$this->area:false,
    'word' => isset($this->word)?$this->word:'',
)) ?>
<nav class="mainmenu">
    <div class="wrapper">
        <ul>
            <li><a href="#">САЛОНЫ</a>
                <a class="quantity" href="#">12</a>
            </li>
            <li><a href="">ДЕВУШКИ</a>
                <a class="quantity" href="#">152</a>
            </li>
            <li><a href="">Акции и скидки </a>
                <a class="quantity" href="#">7</a>
            </li>
            <li><a href="">ВСЕ ОТЗЫВЫ </a></li>
            <li><a href="">Виды массажа</a></li>
            <li><a href="">Статьи</a></li>
        </ul>
        <a class="add-salon" href="#">Добавить салон</a>
        <a class="login" href="#">Войти</a>

    </div>
</nav>
    <?php echo $this->layout()->content ?>

    <?php echo $this->partial('blocks/footer.phtml', array (
                                                           'blocks'      => $this->blocks,
                                                           'siteSetings' => $this->siteSetings

                                                     )) ?>
    <link rel="stylesheet" type="text/css" href="/static/default/css/style.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/adaptive.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/fotorama.css" media="screen"/>
    <script type="text/javascript" src="/static/default/js/script.js"></script>
    <?=$this->headScript()?>
    <script type="text/javascript" src="/static/default/js/more.js"></script>
    <script src="/static/default/js/jquery.lazyload.min.js" type="text/javascript"></script>
<!--    --><?//=$this->siteSetings->getBody();?>
</body>
</html>
