<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="models-content">
<div class="wrapper">
<aside class="left-sidebar">
    <?=$this->ShowWidgetSalons();?>
    <?=$this->ShowWidgetSubscribe();?>
    <?=$this->ShowWidgetAdvertisings();?>
    <?=$this->ShowWidgetComments();?>
    <?=$this->ShowWidgetNewSalons();?>
</aside>
<div class="content-right">
    <article>
        <h2>Весь эротический массаж в Украине</h2>
        <p>Сайт <a href="#">My-Relax</a> самый полный каталог салонов эротического массажа в Киеве и Украине. Для
            каждого салона Вы найдете: краткое описание, географическое месторасположение на карте города, фотографии
            девушек, отзывы и рейтинги от посетителей салонов, виды эротического массажа и его стоимость.</p>
    </article>
<!--    <div class="salon-filter">-->
<!--        <label>-->
<!--            <span>Все массажистки в</span>-->
<!--            <select>-->
<!--                <option disabled>Украине</option>-->
<!--                <option value="ua">Украине</option>-->
<!--                <option value="ru">России</option>-->
<!--            </select>-->
<!--        </label>-->
<!--    </div>-->
    <?php foreach ($this->salons->data as $k => $salon) : ?>
        <? $contentSalon = $salon->getContent()->getFields();?>
        <article class="salon-item-article">
            <div class="salon-model-box">
                <div class="salon-site"><h2><?=$contentSalon->getFText('name');?></h2> <a href="<?=$contentSalon->getFText('url');?>"><?=$contentSalon->getFText('url');?></a></div>
                <div class="salon-model">
                    <? foreach ($salon->getGirls() as $k=>$girl): ?>
                        <? $content = $girl->getContent()->getFields();?>
                        <div class="model-item-box">
                            <div class="model-item">
                                <div class="name">
                                    <a href="<?=$girl->path()?>"><?=$content['name']->getFieldText();?></a>, <?=$girl->getAge();?>
                                </div>
                                <? $galery = $girl->getGallery(); ?>
                                <? if (!is_null($galery)): ?>
                                    <a href="<?=$girl->path()?>">
                                        <? $photo = $galery->getFirstPhoto(); ?>
                                        <img src="<?=$photo->getPath('150', true);?>" width="150px" alt="Массажистка <?=$content['name']->getFieldText();?>">
                                    </a>
                                <? endif; ?>
                                <a class="comment-value"><?=count($girl->getComments())?> отзывов</a>
                            </div>
                        </div>
                    <? endforeach; ?>
                    <div class="clear"></div>
                </div>
            </div>
        </article>
    <? endforeach; ?>

    <div class="pagination-box">
        <a class="prev-pagin-link" href="#">&larr; Предыдущая</a>
        <a href="#">1</a>
        <a href="#">2</a>
        <a href="#">3</a>
        <a href="#">4</a>
        <span>5</span>
        <a href="#">6</a>
        <a href="#">7</a>
        <a href="#">8</a>
        <a href="#">9</a>
        <a href="#">10</a>
        <a href="#">11</a>
        <a href="#">12</a>
        <a href="#">13</a>
        <a href="#">14</a>
        <a href="#">15</a>
        <a class="next-pagin-link" href="#">Следующая &rarr;</a>
    </div>
</div>
</div>
</sections>