<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<? $gallery = $this->girl->getGallery(); ?>
<? $photos = $gallery->getPhotos(); ?>
<sections class="model-content">
    <div class="wrapper">
        <div class="content-left">
            <div class="breadcrumbs">
                <a href="#">Главная</a> &gt;
                <a href="#">Девушки</a> &gt;
                <a href="#">Red Light</a>
            </div>
            <div class="salon-content">
                <h1><?=$this->contentPage->getFText('name'); ?> из салона <?=$this->salonContent->getFText('name')?></h1>

                <div class="first-cell">
                    <a href="#"><img src="images/model-item-single.png"></a>
                </div>
                <div class="second-cell">
                    <div class="desc">
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Возраст:</span>
                            </div>
                            <div class="item-value"><?=$this->girl->getAge();?> лет</div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Размер груди:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('grudi'); ?>-й размер</div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Вес:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('ves'); ?> кг</div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Талия:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('talia'); ?> см</div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Рост:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('rost'); ?> см</div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Бедра:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('bedra'); ?> см</div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Волосы:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('volos'); ?></div>
                        </div>
                        <div class="desc-item-box">
                            <div class="desc-item">
                                <span>Глаза:</span>
                            </div>
                            <div class="item-value"><?=$this->contentPage->getFText('glaz'); ?></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="more-info">
                <span class="white-lable">Посмотреть других девушек салона</span></br>
                <span class="red-lable">и узнать про удовольствия в салоне</span>
                <a href="#"><?=$this->salonContent->getFText('url')?></a>
            </div>
            <? if (count($photos) > 0): ?>
                <div class="relax-recommends">
                    <div class="header">
                        Фото девушки
                    </div>
                    <div class="model-item-container">
                        <div class="fotorama" data-navPosition="right" data-shadows="false" data-vertical="true" data-thumbSize="50"
                             data-width="500" data-height="420">
                            <? foreach ($photos as $photo): ?>
                                <a href="<?=$photo->getPath('400', true);?>">
                                    <img src="<?=$photo->getPath('150', true);?>" width="150px" alt="Массажистка <?=$this->contentPage->getFText('name'); ?>">
                                </a>
                            <? endforeach; ?>
                        </div>
                    </div>
                </div>
            <? endif; ?>
            <? $girls = $this->salon->getGirls(); ?>
            <? if (!is_null($girls) && count($girls) > 1): ?>
            <div class="relax-recommends other-models">
                <div class="header">
                    Другие девушки салона
                </div>
                <article class="salon-item-article">
                    <div class="salon-model-box">
                        <div class="salon-model">
                            <div class="model-item-box">
                                <div class="model-item">
                                    <div class="name">
                                        <a href="#">Виктория</a>, 22
                                    </div>
                                    <a href="#"><img src="images/other-models.png"></a>
                                    <a class="comment-value">26 отзывов</a>
                                </div>
                            </div>
                            <div class="model-item-box">
                                <div class="model-item">
                                    <div class="name">
                                        <a href="#">Виктория</a>, 22
                                    </div>
                                    <a href="#"><img src="images/other-models2.png"></a>
                                    <a class="comment-value">26 отзывов</a>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </article>
            </div>
            <? endif; ?>
            <?=$this->ShowSalonSubscribeBox(); ?>
            <div class="new-salon">
                <div class="header">
                    Рекомендуем салоны в городе Киев
                </div>
                <div id="new-salon-carousel" class="content">
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">5 комнат</a>
                            <a href="#"><img src="images/salon-item.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">Milos</a>
                            <a href="#"><img src="images/salon-item-2.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">5 комнат</a>
                            <a href="#"><img src="images/salon-item.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">5 комнат</a>
                            <a href="#"><img src="images/salon-item-2.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">Amur</a>
                            <a href="#"><img src="images/salon-item.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">Milos</a>
                            <a href="#"><img src="images/salon-item-2.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">5 комнат</a>
                            <a href="#"><img src="images/salon-item.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                    <div class="salon-item-box">
                        <div class="salon-item">
                            <a href="#">Amur</a>
                            <a href="#"><img src="images/salon-item-2.png"></a>
                            <span class="city">Киев</span>
                            <a class="comment-value">26 отзывов</a>
                        </div>
                    </div>
                </div>
                <a id="new-salon-prev" href="#"></a>
                <a id="new-salon-next" href="#"></a>
                <a class="all-item-carousel" href="#">Все салоны &rarr;</a>
            </div>
            <div class="new-models">
            <div class="header">
                Популярные девушки города Киев
            </div>
            <div id="new-model-carousel" class="content">
                <div class="new-model-item-box">
                    <div class="new-model-item">
                        <div class="name">
                            <a href="#">Виктория</a>, 22
                        </div>
                        <a href="#"><img src="images/model1g.png"></a>
                        <span class="city">Днепропетровск</span>
                        <a class="comment-value">26 отзывов</a>
                    </div>
                </div>
                <div class="new-model-item-box">
                    <div class="new-model-item">
                        <div class="name">
                            <a href="#">Виктория</a>, 22
                        </div>
                        <a href="#"><img src="images/model2g.png"></a>
                        <span class="city">Днепропетровск</span>
                        <a class="comment-value">26 отзывов</a>
                    </div>
                </div>
                <div class="new-model-item-box">
                    <div class="new-model-item">
                        <div class="name">
                            <a href="#">Виктория</a>, 22
                        </div>
                        <a href="#"><img src="images/model2g.png"></a>
                        <span class="city">Днепропетровск</span>
                        <a class="comment-value">26 отзывов</a>
                    </div>
                </div>
                <div class="new-model-item-box">
                    <div class="new-model-item">
                        <div class="name">
                            <a href="#">Виктория</a>, 22
                        </div>
                        <a href="#"><img src="images/model1g.png"></a>
                        <span class="city">Днепропетровск</span>
                        <a class="comment-value">26 отзывов</a>
                    </div>
                </div>
                <div class="new-model-item-box">
                    <div class="new-model-item">
                        <div class="name">
                            <a href="#">Виктория</a>, 22
                        </div>
                        <a href="#"><img src="images/model2g.png"></a>
                        <span class="city">Днепропетровск</span>
                        <a class="comment-value">26 отзывов</a>
                    </div>
                </div>
                <div class="new-model-item-box">
                    <div class="new-model-item">
                        <div class="name">
                            <a href="#">Виктория</a>, 22
                        </div>
                        <a href="#"><img src="images/model2g.png"></a>
                        <span class="city">Днепропетровск</span>
                        <a class="comment-value">26 отзывов</a>
                    </div>
                </div>
            </div>
            <a id="new-model-prev" href="#"></a>
            <a id="new-model-next" href="#"></a>
            <a class="all-item-carousel" href="#">Все девушки &rarr;</a>
        </div>
        </div>
        <aside class="sidebar-right">
            <div class="sidebar-right-widget">
                <h3>Отзывы о девушке <span>(36)</span></h3>
                <a class="leave-comment" href="#">Оставить отзыв</a>
                <ul>
                    <li>
                        <span class="author">Миша</span>
                        <time>19 мая 2013 в 01:50</time>
                        <p class="author-comment">— Был сегодня в Вашем салоне. Мне очень понравилась массажистка Влада. Заеду
                            еще. Ты мастер своего дела.</p>
                    </li>
                    <li>
                        <span class="author">Миша</span>
                        <time>19 мая 2013 в 01:50</time>
                        <p class="author-comment">— Настя ты просто ангел!!! У тебя прекрасное тело а грудь мм.... Ты
                            профессионал! Рекомендую всем!!!!</p>
                    </li>
                    <li>
                        <span class="author">Миша</span>
                        <time>19 мая 2013 в 01:50</time>
                        <p class="author-comment">— Дорогие мужчины!Спасибо за прекрасные слова в наш адрес.Мы всегда рады Вас
                            видеть.Хотим ответить на ваши отзывы:-Лиза вернулась.А на счет затасканых..тупых..и
                            антисанитарии-могу ответить-это ложь.Достаточно зайти на наш сайт и посмотреть на фото где шикарные
                            девченки в аппартаментах с евроремонтом.Да и встречаем мы всех с улыбкой-так заведено.И уходит от
                            нас ни с чем -один из пятидесяти.А то и отправляем сами если пришел "невминяшка"...А у нашего гостя
                            видимо денег не хватило и ему отказали, вот и расстроился бедолага и решил грязью облить.Но это его
                            мнение и мы его уважаем.А Вам советуем самим убедиться.Приходите,всегда Вам рады.</p>
                    </li>
                </ul>
                <div class="prev-next-comments-box">
                    <a class="prev-comments" href="#">&larr; Предыдущие</a>
                    <a class="next-comments" href="#">Следующие &rarr;</a>
                </div>
            </div>
        </aside>
    </div>
</sections>