<footer>
    <div class="wrapper">
        <nav class="footer-nav">
            <ul>
                <li><a href="/">Салон</a></li>
                <li>
                    <a href="<?=$this->url(array(), 'default-list-girls');?>">Девушки</a>
                </li>
                <li>
                    <a href="<?=$this->url(array(),'default-type-massage')?>">Виды массажа</a>
                </li>
                <li><a href="#">Все отзывы</a></li>
                <li><a href="#">Статьи</a></li>
                <li><a href="#">Услуги для салонов</a></li>
            </ul>
        </nav>
        <div class="copyright">
            <p>Copyright © 2011 – <?=date('Y')?>  my-relax.net</p>
        </div>
        <div class="copyright-desc">
            <p>Все права защищены и охраняются действующим законодательством. </br> Использование материалов с данного сайта возможно только при наличии гиперссылки my-relax.net. </br> Администрация сайта не несет ответственности за содержание размещенных объявлений.</p>
        </div>
        <div class="clear"></div>
    </div>
</footer>
<?//=Kernel_Block::getText('footer', $this->blocks);?>