<nav class="mainmenu">
    <div class="wrapper">
        <ul>
            <li><a href="/">САЛОНЫ</a>
                <a class="quantity" href="#">12</a>
            </li>
            <li>
                <a href="<?=$this->url(array(), 'default-list-girls');?>">ДЕВУШКИ</a>
                <a class="quantity" href="#">152</a>
            </li>
            <li>
                <a href="<?=$this->url(array(),'default-list-discount')?>">Акции и скидки</a>
                <a class="quantity" href="#">7</a>
            </li>
            <li>
                <a href="<?=$this->url(array(),'default-page-reviews')?>">ВСЕ ОТЗЫВЫ</a>
            </li>
            <li>
                <a href="<?=$this->url(array(),'default-list-vacancy')?>">Вакансии</a>
            </li>
            <li>
                <a href="<?=$this->url(array(),'default-type-massage')?>">Виды массажа</a>
            </li>
            <li>
                <a href="<?=$this->url(array(), 'default-list-article')?>">Статьи</a>
            </li>
        </ul>
<!--        <a class="add-salon" href="#">Добавить салон</a>-->
<!--        <a class="login" href="#">Войти</a>-->
    </div>
</nav>