<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="discount-content">
    <div class="wrapper">
        <aside class="left-sidebar">
            <div class="sidebar-widget salons">
                <h3>Салоны</h3>
                <ul>
                    <li><a href="#">Киев</a>
                        <ul class="sub-menu">
                            <li><a href="#">Дарницкий</a></li>
                            <li><a href="#">Подольский</a></li>
                            <li><a href="#">Печерский</a></li>
                            <li><a href="#">Шевченковский</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Днепропетровск</a>
                        <ul class="sub-menu">
                            <li><a href="#">Дарницкий</a></li>
                            <li><a href="#">Подольский</a></li>
                            <li><a href="#">Печерский</a></li>
                            <li><a href="#">Шевченковский</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Одесса</a>
                        <ul class="sub-menu">
                            <li><a href="#">Дарницкий</a></li>
                            <li><a href="#">Подольский</a></li>
                            <li><a href="#">Печерский</a></li>
                            <li><a href="#">Шевченковский</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Донецк</a>
                        <ul class="sub-menu">
                            <li><a href="#">Дарницкий</a></li>
                            <li><a href="#">Подольский</a></li>
                            <li><a href="#">Печерский</a></li>
                            <li><a href="#">Шевченковский</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Харьков</a>
                        <ul class="sub-menu">
                            <li><a href="#">Дарницкий</a></li>
                            <li><a href="#">Подольский</a></li>
                            <li><a href="#">Печерский</a></li>
                            <li><a href="#">Шевченковский</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Винница</a>
                        <ul class="sub-menu">
                            <li><a href="#">Дарницкий</a></li>
                            <li><a href="#">Подольский</a></li>
                            <li><a href="#">Печерский</a></li>
                            <li><a href="#">Шевченковский</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="all-salons-link-box">
                    <a class="all-salons" href="#">Весь список салонов &rarr;</a>
                </div>
            </div>
            <div class="sidebar-widget subscribe-widget">
                <span class="subs-white"><span>Подпишись</span> на нашу рассылку</span>
                <span class="subs-red">и всегда будь в курсе:</span>
                <ul>
                    <li>новых девушек на портале</li>
                    <li>новых салонов в нашем каталоге</li>
                    <li>новых возможностях наслаждения</li>
                </ul>
                <form>
                    <span>Ваша электронная почта</span>
                    <input type="text" name="" id=""/>
                    <input type="submit" name="" id="" value=""/>
                </form>
            </div>
            <div class="sidebar-widget adv">
                <h3></h3>
                <a href="#"><img src="images/banner-sb.png"></a>
            </div>
            <div class="sidebar-widget comments-widget">
                <h3>Отзывы</h3>
                <ul>
                    <li>
                        <a href="#"><img src="images/ava.png"></a>
                        <a class="author" href="#">Mon - Amour</a>
                        <time>19 мая 2013 в 01:50</time>
                        <a class="comment" href="#">— Я покупала сертификат для своего мужчины. Большое спасибо, девушкам Даше и
                            Асе.</a>

                        <div class="clear"></div>
                    </li>
                    <li>
                        <a href="#"><img src="images/ava.png"></a>
                        <a class="author" href="#">Mon - Amour</a>
                        <time>19 мая 2013 в 01:50</time>
                        <a class="comment" href="#">— Я покупала сертификат для своего мужчины. Большое спасибо, девушкам Даше и
                            Асе.</a>

                        <div class="clear"></div>
                    </li>
                    <li>
                        <a href="#"><img src="images/ava.png"></a>
                        <a class="author" href="#">Mon - Amour</a>
                        <time>19 мая 2013 в 01:50</time>
                        <a class="comment" href="#">— Я покупала сертификат для своего мужчины. Большое спасибо, девушкам Даше и
                            Асе.</a>

                        <div class="clear"></div>
                    </li>
                </ul>
                <div class="all-link-right">
                    <a href="#" class="all-comments">Все отзывы &rarr;</a>
                </div>
            </div>
            <div class="sidebar-widget newsalon-widget">
                <h3>Новые салоны</h3>
                <ul>
                    <li>
                        <a href="#"><img src="images/salon-item.png"></a>
                        <a class="salon-name" href="#">Mon - Amour</a>
                        <span>Киев</span>
                        <span class="street" href="#">ул. Киквидзе, 1а</span>

                        <div class="clear"></div>
                    </li>
                    <li>
                        <a href="#"><img src="images/salon-item.png"></a>
                        <a class="salon-name" href="#">Mon - Amour</a>
                        <span>Киев</span>
                        <span class="street" href="#">ул. Киквидзе, 1а</span>

                        <div class="clear"></div>
                    </li>
                    <li>
                        <a href="#"><img src="images/salon-item.png"></a>
                        <a class="salon-name" href="#">Mon - Amour</a>
                        <span>Киев</span>
                        <span class="street" href="#">ул. Киквидзе, 1а</span>

                        <div class="clear"></div>
                    </li>
                </ul>
                <div class="all-link-right">
                    <a href="#" class="all-comments">Все салоны &rarr;</a>
                </div>
            </div>
        </aside>
        <div class="content-right">
            <div class="salon-filter">
                <label>
                    <span>Статьи и новости мира салонов эротического массажа </span>
                </label>
            </div>
            <?=$this->ShowSalonSubscribeBox()?>
            <? foreach ($this->masses->data as $mass): ?>
                <? $massContent = $mass->getContent()->getFields(); ?>
                <div class="post-box">
                    <h2><a href="<?=$mass->getRoute()->getUrl();?>"><?=$massContent['name']->getFieldText();?></a></h2>
                    <div class="post-text"><?=$massContent['desc']->getFieldText();?></div>
                    <a class="readmore-post" href="<?=$mass->getRoute()->getUrl();?>">Подробнее &rarr;</a>
                    <div class="clear"></div>
                </div>
            <? endforeach;?>
            <?=$this->paginationControl($this->masses->paginator, 'Sliding', 'block/paginator_mass.phtml'); ?>
        </div>
    </div>
</sections>
<!--<div class="singleSalonBox">-->
<!--    <div class="salonContent">-->
<!--        --><?//=$this->ShowSubscribe();?>
<!--        <div class="descText" style="margin-top: 10px; padding: 20px;">-->
<!--            <h1>Виды массажа</h1>-->
<!--            --><?// foreach ($this->masses->data as $mass): ?>
<!--                --><?// $massContent = $mass->getContent()->getFields(); ?>
<!--                <article>-->
<!--                    <div style="float: left; width: 80%">-->
<!--                        <a href="--><?//=$mass->getRoute()->getUrl();?><!--" class="mass_list_title">--><?//=$massContent['name']->getFieldText();?><!--</a>-->
<!--                        <p>--><?//=$massContent['desc']->getFieldText();?><!--</p>-->
<!--                    </div>-->
<!--                    <div style="float:right; padding: 5px; border: 1px solid #fff;">-->
<!--                        <img src="--><?//=$mass->getPhoto1()->getPath('90:90');?><!--"  width="90" height="90"/>-->
<!--                    </div>-->
<!--                </article>-->
<!--                <hr/>-->
<!--            --><?// endforeach;?>
<!--            --><?//=$this->paginationControl($this->masses->paginator, 'Sliding', 'block/paginator_mass.phtml'); ?>
<!--        </div>-->
<!--        <div class="clear"></div>-->
<!--        --><?//=$this->ShowSubscribe();?>
<!--    </div>-->
<!--</div>-->