<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="discount-content">
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <?=$this->ShowWidgetSubscribe();?>
            <?=$this->ShowWidgetBanner();?>
            <?=$this->ShowWidgetComments();?>
            <?=$this->ShowWidgetNewSalons();?>
        </aside>
        <div class="content-right">
            <div class="salon-filter">
                <label>
                    <span>Статьи и новости мира салонов эротического массажа </span>
                </label>
            </div>
            <?=$this->ShowSalonSubscribeBox()?>
            <? foreach ($this->masses->data as $mass): ?>
                <? $massContent = $mass->getContent()->getFields(); ?>
                <div class="post-box">
                    <h2><a href="<?=$mass->getRoute()->getUrl();?>"><?=$massContent['name']->getFieldText();?></a></h2>
                    <div class="post-text"><?=$massContent['desc']->getFieldText();?></div>
                    <a class="readmore-post" href="<?=$mass->getRoute()->getUrl();?>">Подробнее &rarr;</a>
                    <div class="clear"></div>
                </div>
            <? endforeach;?>
            <?=$this->paginationControl($this->masses->paginator, 'Sliding', 'block/paginator_mass.phtml'); ?>
        </div>
    </div>
</sections>
<!--<div class="singleSalonBox">-->
<!--    <div class="salonContent">-->
<!--        --><?//=$this->ShowSubscribe();?>
<!--        <div class="descText" style="margin-top: 10px; padding: 20px;">-->
<!--            <h1>Виды массажа</h1>-->
<!--            --><?// foreach ($this->masses->data as $mass): ?>
<!--                --><?// $massContent = $mass->getContent()->getFields(); ?>
<!--                <article>-->
<!--                    <div style="float: left; width: 80%">-->
<!--                        <a href="--><?//=$mass->getRoute()->getUrl();?><!--" class="mass_list_title">--><?//=$massContent['name']->getFieldText();?><!--</a>-->
<!--                        <p>--><?//=$massContent['desc']->getFieldText();?><!--</p>-->
<!--                    </div>-->
<!--                    <div style="float:right; padding: 5px; border: 1px solid #fff;">-->
<!--                        <img src="--><?//=$mass->getPhoto1()->getPath('90:90');?><!--"  width="90" height="90"/>-->
<!--                    </div>-->
<!--                </article>-->
<!--                <hr/>-->
<!--            --><?// endforeach;?>
<!--            --><?//=$this->paginationControl($this->masses->paginator, 'Sliding', 'block/paginator_mass.phtml'); ?>
<!--        </div>-->
<!--        <div class="clear"></div>-->
<!--        --><?//=$this->ShowSubscribe();?>
<!--    </div>-->
<!--</div>-->