<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<sections class="post-content">
    <div class="wrapper">
        <aside class="left-sidebar">
            <?=$this->ShowWidgetSalons();?>
            <div class="sidebar-widget adv">
                <h3></h3>
                <a href="#"><img src="images/banner-sb.png"></a>
            </div>
            <?=$this->ShowWidgetComments();?>


            <div class="sidebar-widget">
                <h3>Акции</h3>
                <ul>
                    <li>
                        <time>19 мая 2013 в 01:50</time>
                        <a href="#">Достойный массажный салон должен быть достойным во всем</a>
                        <div class="clear"></div>
                    </li>
                    <li>
                        <time>19 мая 2013 в 01:50</time>
                        <a href="#">Интимный массаж не только возбуждает</a>
                        <div class="clear"></div>
                    </li>
                    <li>
                        <time>19 мая 2013 в 01:50</time>
                        <a href="#">Тайский массаж - не всегда эротический</a>
                        <div class="clear"></div>
                    </li>
                </ul>
                <div class="all-link-right">
                    <a href="#" class="all-link">Все акции &rarr;</a>
                </div>

            </div>

            <div class="sidebar-widget">
                <h3>Статьи</h3>
                <ul>
                    <li>
                        <time>19 мая 2013 в 01:50</time>
                        <a href="#">Достойный массажный салон должен быть достойным во всем</a>
                        <div class="clear"></div>
                    </li>
                    <li>
                        <time>22 мая 2013 в 12:50</time>
                        <a href="#">Интимный массаж не только возбуждает</a>
                        <div class="clear"></div>
                    </li>
                    <li>
                        <time>07 мая 2013 в 11:50</time>
                        <a href="#">Тайский массаж - не всегда эротический</a>
                        <div class="clear"></div>
                    </li>
                </ul>
                <div class="all-link-right">
                    <a href="#" class="all-link">Все статьи &rarr;</a>
                </div>

            </div>
        </aside>
        <div class="content-right">
            <article class="discount-box">
                <h2><?=$this->contentPage['name']->getFieldText();?></h2>
                <img class="alingleft" src="<?=$this->mass->getPhoto1()->getPath('350', true)?>" width="350px">
                <?=$this->contentPage['content']->getFieldText();?>
            </article>
            <?=$this->ShowSalonSubscribeBox()?>
        </div>
    </div>
</sections>
<!--<style>-->
<!--    .descText img {-->
<!--        max-width: 350px;-->
<!--        float: right;-->
<!--        margin: 0 15px;-->
<!--        padding: 5px;-->
<!--        border: 1px solid #fff;-->
<!--    }-->
<!--</style>-->
<!--<div class="singleSalonBox">-->
<!--    <div class="salonContent">-->
<!--        --><?//=$this->ShowSubscribe();?>
<!--        <div class="descText" style="margin-top: 10px; padding: 20px;">-->
<!--            <article>-->
<!--                <span style="margin-bottom: 10px; display: block;">-->
<!--                    <a style="color:#a7a6a6" href="--><?//=$this->url(array(),'default-type-massage')?><!--"><< Все виды массажа</a>-->
<!--                </span>-->
<!--                <h1></h1>-->
<!--                <img src="--><?//=$this->mass->getPhoto1()->getPath('350', true)?><!--"/>-->
<!--                <table border="0" cellpadding="5" cellspacing="5" style="font-size: 12.0120115280151px; width: 500px;">-->
<!--                    <tbody>-->
<!--                    <tr>-->
<!--                        <td>-->
<!--                            <p style="margin-left: 1.5pt; text-align: justify;">-->
<!--                                --><?//=isset($this->contentPage['paragraf'])?$this->contentPage['paragraf']->getFieldText():'';?><!--</p>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    </tbody>-->
<!--                </table>-->
<!--                <table border="0" cellpadding="5" cellspacing="5" style="font-size: 12.0120115280151px; width: 800px;">-->
<!--                    <tbody>-->
<!--                    <tr>-->
<!--                        <td>-->
<!--                            <p style="margin-left: 1.5pt; text-align: justify;">--><?//=$this->contentPage['content']->getFieldText();?><!--</p>-->
<!--                        </td>-->
<!--                        <td>-->
<!--                            --><?//=$this->siteSetings->getMassLinks();?>
<!--                        </td>-->
<!--                    </tr>-->
<!--                    </tbody>-->
<!--                </table>-->
<!---->
<!--            </article>-->
<!--        </div>-->
<!--        <div class="clear"></div>-->
<!--        --><?//=$this->ShowSubscribe();?>
<!--    </div>-->
<!--</div>-->